PUSH=calc.commands.PushCommand
POP=calc.commands.PopCommand
+=calc.commands.AddCommand
-=calc.commands.SubCommand
*=calc.commands.MulCommand
/=calc.commands.DivCommand
DIV=calc.commands.DivCommand
ADD=calc.commands.AddCommand
SQRT=calc.commands.SqrtCommand
PRINT=calc.commands.PrintCommand
DEFINE=calc.commands.DefineCommand
